name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: IONOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npx gulp build

        jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Enable Debug Mode
        run: |
          echo "Debugging enabled"
          echo "SSH_HOST: ${SSH_HOST:0:5}..."
          echo "SSH_USERNAME: ${SSH_USERNAME:0:5}..."
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

      - name: Deploy to server via SFTP
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          # Save the SSH private key to a file
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # Use rsync to copy the dist/ folder to the remote server
          rsync -avz -e "ssh -i key.pem" ./dist/ $SSH_USERNAME@$SSH_HOST:$REMOTE_PATH

          # Clean up the SSH key file
          rm key.pem
